Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Salary_Management.Data;
using App_Salary_Management.Models;
using Microsoft.AspNetCore.Authorization;

namespace App_Salary_Management.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Employees.Include(e => e.Department);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: test/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .FirstOrDefaultAsync(m => m.EmployeeID == id);
            if (employee == null)
            {
                return NotFound();
            }


            return View(employee);
        }

        // GET: test/Create
        public IActionResult Create()
        {
            ViewData["DepartmentID"] = new SelectList(_context.Departments, "DepartmentID", "Name");
            return View();
        }

        // POST: test/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("EmployeeID,Name,Email,Phone,Address,BaseSalary,DepartmentID")]
            Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["DepartmentID"] =
                new SelectList(_context.Departments, "DepartmentID", "Name", employee.DepartmentID);
            return View(employee);
        }

        // GET: test/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            ViewData["DepartmentID"] =
                new SelectList(_context.Departments, "DepartmentID", "Name", employee.DepartmentID);
            return View(employee);
        }

        // POST: test/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("EmployeeID,Name,Email,Phone,Address,BaseSalary,DepartmentID")]
            Employee employee)
        {
            if (id != employee.EmployeeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["DepartmentID"] =
                new SelectList(_context.Departments, "DepartmentID", "Name", employee.DepartmentID);
            return View(employee);
        }

        // GET: test/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .FirstOrDefaultAsync(m => m.EmployeeID == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: test/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Employees == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Employees'  is null.");
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return (_context.Employees?.Any(e => e.EmployeeID == id)).GetValueOrDefault();
        }
    }
}

Controllers/SalaryController.cs
using App_Salary_Management.Data;
using App_Salary_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace App_Salary_Management.Controllers;

[Authorize]
public class SalaryController : Controller
{
    private readonly ApplicationDbContext _context;

    public SalaryController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET
    public IActionResult Index()
    {
        var result = _context.TimeSheets
            .Join(_context.Employees, ts => ts.EmployeeId, e => e.EmployeeID,
                (e, ts) => new { e, ts })
            .GroupBy(x => new { x.e.EmployeeId, x.e.date.Month, x.e.date.Year })
            .Select(g => new
            {
                g.Key.EmployeeId,
                month = g.Key.Month,
                year = g.Key.Year,
                Count = g.Count()
            }).Join(_context.Employees, arg => arg.EmployeeId,
                employee => employee.EmployeeID, (arg, e) =>
                    new Salary
                    {
                        EmployeeID = e.EmployeeID,
                        Address = e.Address,
                        Email = e.Email,
                        Name = e.Name,
                        Phone = e.Phone,
                        BaseSalary = e.BaseSalary,
                        Salaryb = e.BaseSalary * arg.Count,
                        Moth = arg.month,
                        year = arg.year,
                        WorkNumberDay = arg.Count
                    }
            ).ToList();

        return View(result);
    }
}

Controllers/TimeSheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Salary_Management.Data;
using App_Salary_Management.Models;
using Microsoft.AspNetCore.Authorization;

namespace App_Salary_Management.Controllers
{
    [Authorize]
    public class TimeSheetController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TimeSheetController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TimeSheet
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.TimeSheets.Include(t => t.Employee);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: TimeSheet/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TimeSheets == null)
            {
                return NotFound();
            }

            var timeSheet = await _context.TimeSheets
                .Include(t => t.Employee)
                .FirstOrDefaultAsync(m => m.TimeSheetID == id);
            if (timeSheet == null)
            {
                return NotFound();
            }

            return View(timeSheet);
        }

        // GET: TimeSheet/Create
        public IActionResult Create()
        {
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeID", "Name");
            return View();
        }

        // POST: TimeSheet/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TimeSheetID,date,EmployeeId,Status")] TimeSheet timeSheet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(timeSheet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeID", "Name", timeSheet.EmployeeId);
            return View(timeSheet);
        }

        // GET: TimeSheet/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TimeSheets == null)
            {
                return NotFound();
            }

            var timeSheet = await _context.TimeSheets.FindAsync(id);
            if (timeSheet == null)
            {
                return NotFound();
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeID", "Name", timeSheet.EmployeeId);
            return View(timeSheet);
        }

        // POST: TimeSheet/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TimeSheetID,date,EmployeeId")] TimeSheet timeSheet)
        {
            if (id != timeSheet.TimeSheetID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timeSheet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeSheetExists(timeSheet.TimeSheetID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeID", "Name", timeSheet.EmployeeId);
            return View(timeSheet);
        }

        // GET: TimeSheet/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TimeSheets == null)
            {
                return NotFound();
            }

            var timeSheet = await _context.TimeSheets
                .Include(t => t.Employee)
                .FirstOrDefaultAsync(m => m.TimeSheetID == id);
            if (timeSheet == null)
            {
                return NotFound();
            }

            return View(timeSheet);
        }

        // POST: TimeSheet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TimeSheets == null)
            {
                return Problem("Entity set 'ApplicationDbContext.TimeSheets'  is null.");
            }

            var timeSheet = await _context.TimeSheets.FindAsync(id);
            if (timeSheet != null)
            {
                _context.TimeSheets.Remove(timeSheet);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimeSheetExists(int id)
        {
            return (_context.TimeSheets?.Any(e => e.TimeSheetID == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Quản lý lương</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/> *@
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/> *@
    @* <link rel="stylesheet" href="~/App_Salary_Management.styles.css" asp-append-version="true"/> *@

    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <!-- Custom styles for this page -->
    <link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>
@* <body> *@
@* <header> *@
@*     <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
@*         <div class="container-fluid"> *@
@*             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">App_Salary_Management</a> *@
@*             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
@*                     aria-expanded="false" aria-label="Toggle navigation"> *@
@*                 <span class="navbar-toggler-icon"></span> *@
@*             </button> *@
@*             <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
@*                 <ul class="navbar-nav flex-grow-1"> *@
@*                     <li class="nav-item"> *@
@*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
@*                     </li> *@
@*                     <li class="nav-item"> *@
@*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
@*                     </li> *@
@*                 </ul> *@
@*                 <partial name="_LoginPartial"/> *@
@*             </div> *@
@*         </div> *@
@*     </nav> *@
@* </header> *@
@* <div class="container"> *@
@*     <main role="main" class="pb-3"> *@
@*         @RenderBody() *@
@*     </main> *@
@* </div> *@
@* *@
@* <footer class="border-top footer text-muted"> *@
@*     <div class="container"> *@
@*         &copy; 2022 - App_Salary_Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
@*     </div> *@
@* </footer> *@
@* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
@* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
@* <script src="~/js/site.js" asp-append-version="true"></script> *@
@* @await RenderSectionAsync("Scripts", false) *@
@* </body> *@

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <a class="sidebar-brand d-flex align-items-center justify-content-center">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Thành Công</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Nav Item -->
        <li class="nav-item">
            <a class="nav-link" asp-controller="Employee" asp-action="Index">
                <i class="fas fa-fw fa-table"></i>
                <span>Nhân viên</span>
            </a>
        </li>
        <!-- Nav Item -->
        <li class="nav-item">
            <a class="nav-link" asp-controller="TimeSheet" asp-action="Index">
                <i class="fas fa-fw fa-table"></i>
                <span>Điểm danh</span>
            </a>
        </li>
        <!-- Nav Item -->
        <li class="nav-item">
            <a class="nav-link" asp-controller="Department" asp-action="Index">
                <i class="fas fa-fw fa-table"></i>
                <span>Phòng ban</span>
            </a>
        </li>
        <!-- Nav Item -->
        <li class="nav-item">
            <a class="nav-link" asp-controller="Salary" asp-action="Index">
                <i class="fas fa-fw fa-table"></i>
                <span>Lương</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>


    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            @* <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"> *@
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Salary" asp-action="Index">Ứng dụng quản lý lương</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <partial name="_LoginPartial"/>
                    </div>
                </div>
            </nav>
            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">
                @RenderBody()
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; genson1808</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="~/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="~/vendor/chart.js/Chart.min.js"></script>

<!-- Page level custom scripts -->
<script src="~/js/demo/chart-area-demo.js"></script>
<script src="~/js/demo/chart-pie-demo.js"></script>

<!-- Page level plugins -->
<script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="~/js/demo/datatables-demo.js"></script>

@* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
@* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
@* <script src="~/js/site.js" asp-append-version="true"></script> *@


<script>
$.fn.dataTable.ext.search.push(function (settings, data, dataIndex) {
    var month = parseInt($('#month').val(), 10);
    var year = parseInt($('#year').val(), 10);
    var monthData  = parseFloat(data[7]) || 0; // use data for the age column
    var yearData = parseFloat(data[8]) || 0; // use data for the age column
 
    if (
         (isNaN(month) && isNaN(year)) ||
        (isNaN(year) && monthData === month) ||
        (isNaN(month) && yearData === year) ||
        (month === monthData && year === yearData)
    ) {
        return true;
    }
    return false;
});
 
$(document).ready(function () {
    var table = $('#dataTable').DataTable();
 
    // Event listener to the two range filtering inputs to redraw on input
    $('#month, #year').keyup(function () {
        table.draw();
    });
});
</script>

@await RenderSectionAsync("Scripts", false)
</body>

</html>